### ISSUE TITLE
`SIGTRAP` in message_free when closing uTox.

### ISSUE THREAD

**Issue by robinlinden** [uTox/uTox#1049]
```
#0  0x00007ffab1dcc4cf in ntdll!RtlpNtMakeTemporaryKey () from /cygdrive/c/WINDO
WS/SYSTEM32/ntdll.dll
#1  0x00007ffab1d9829a in ntdll!memset () from /cygdrive/c/WINDOWS/SYSTEM32/ntdl
l.dll
#2  0x00007ffab1d63d01 in ntdll!EtwEventProviderEnabled () from /cygdrive/c/WIND
OWS/SYSTEM32/ntdll.dll
#3  0x00007ffab1d8df51 in ntdll!memset () from /cygdrive/c/WINDOWS/SYSTEM32/ntdl
l.dll
#4  0x00007ffab1d0cfb6 in ntdll!RtlFreeHeap () from /cygdrive/c/WINDOWS/SYSTEM32
/ntdll.dll
#5  0x00007ffab1169dac in msvcrt!free () from /cygdrive/c/WINDOWS/System32/msvcr
t.dll
#6  0x00000000004113c7 in message_free (msg=0x7f2dbe0) at /cygdrive/d/Projects/T
ox/uToxx/src/messages.c:1791
#7  0x000000000040a221 in friend_free (f=0x80678e8) at /cygdrive/d/Projects/Tox/
uToxx/src/friend.c:476
        msg = 0x7f2dbe0
        i = 250
#8  0x00000000004090d6 in free_friends () at /cygdrive/d/Projects/Tox/uToxx/src/
friend.c:124
        f = 0x80678e8
        i = 1
#9  0x0000000000430f95 in toxcore_thread (UNUSED_args=0x0) at /cygdrive/d/Projec
ts/Tox/uToxx/src/tox.c:504
        tox = 0x4619d70
        av = 0x80be200
        reconfig = false
        toxcore_init_err = 0
```

**Comment by robinlinden** [comment]
Actually, this is on an older branch, so this is probably not relevant anymore.
