### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by crypto-universe** [uTox/uTox#1123]
I've downloaded an uTox 0.16.1 alpha from repo (Ubuntu 16.04 x64) and see such output in console:
```
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
AL lib: (WW) alcCloseDevice: Releasing context 0x61200003b2c0

=================================================================
==31941==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 26928 byte(s) in 198 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f27ce6c61b0 in XCreateImage (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x271b0)

Direct leak of 15424 byte(s) in 482 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f27ce04de6e  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xde6e)

Direct leak of 6656 byte(s) in 26 object(s) allocated from:
    #0 0x7f27d04ff602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f27ce05d0b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Direct leak of 4096 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7f27ce04dac3  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xdac3)

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7f27ce04dad4  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xdad4)

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x474992  (/usr/bin/utox+0x474992)
    #2 0x475747 in native_window_create_main (/usr/bin/utox+0x475747)
    #3 0x41322a in main (/usr/bin/utox+0x41322a)
    #4 0x7f27d00bd82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x47499e  (/usr/bin/utox+0x47499e)
    #2 0x475747 in native_window_create_main (/usr/bin/utox+0x475747)
    #3 0x41322a in main (/usr/bin/utox+0x41322a)
    #4 0x7f27d00bd82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f27d0128489 in __strdup (/lib/x86_64-linux-gnu/libc.so.6+0x8b489)
    #2 0x657628202961686f  (<unknown module>)

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f27ce6d8379 in XStringListToTextProperty (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x39379)
    #2 0x7f27d046049f  (/lib/x86_64-linux-gnu/libc.so.6+0x3c349f)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x4749aa  (/usr/bin/utox+0x4749aa)
    #2 0x475747 in native_window_create_main (/usr/bin/utox+0x475747)
    #3 0x41322a in main (/usr/bin/utox+0x41322a)
    #4 0x7f27d00bd82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 1632 byte(s) in 51 object(s) allocated from:
    #0 0x7f27d04ff79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f27ce05d7c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

Indirect leak of 519 byte(s) in 50 object(s) allocated from:
    #0 0x7f27d04ff602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f27d0128489 in __strdup (/lib/x86_64-linux-gnu/libc.so.6+0x8b489)

SUMMARY: AddressSanitizer: 56493 byte(s) leaked in 814 allocation(s).
```
It has no debug symbols and stripped :(
`
/usr/bin/utox: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=a905ced13fc92da74814ed37dfcdb898e812edbe, stripped
`

**Comment by GrayHatter** [comment]
likely wontfix, I'm not going to close this yet, as we should take a look. But the fontconfig leaks aren't ours. And the other leaks are related to xlib, which we need and use, right up until uTox exits. So there's no reason to free them.

**Comment by redmanmale** [comment]
But ASAN will be disabled for release builds (#1026) and there won't be any of this warnings.
