### ISSUE TITLE
Crash on video call

### ISSUE THREAD

**Issue by endoffile78** [uTox/uTox#1131]
OS: Ubuntu 17.04
effected branches: master and develop
reported by mannol

stacktrace: 
```
#4 0x7f15bebb6e84 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc6e84)    
#5 0x56371bd5394b in video_frame (/home/mannol/Documents/Software/uTox/utox+0x9694b)          
#6 0x56371bd8a910 in utox_message_dispatch (/home/mannol/Documents/Software/uTox/utox+0xcd910)
#7 0x56371bd727e8 in doevent (/home/mannol/Documents/Software/uTox/utox+0xb57e8)              
#8 0x56371bd68459 in main (/home/mannol/Documents/Software/uTox/utox+0xab459)                 
```

**Comment by GrayHatter** [comment]
@mannol compile with debugging symbols added again.

Without a line number, or a better clue as to the location, I can't fix this.
