### ISSUE TITLE
utox crashes at start

### ISSUE THREAD

**Issue by pizdjuk** [uTox/uTox#1165]
### Overview

1. uTox version: 0.16.1-4, from ubuntu 16.04 nightly repo
2. Operating system: linux mint 18.3
3. Desktop Environment/Window Manager (Linux/BSD only): MATE

### Issue

0.16.1-4 utox crashes at start. 0.16.1 works ok, but video does not (white screen with errors in a console)

Terminal output:

dikiy@rosh:~$ utox
ASAN:SIGSEGV
=================================================================
==11381==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000a23 (pc 0x00000045c79b bp 0x7ffe0c4d5e10 sp 0x7ffe0c4d5d30 T0)
    #0 0x45c79a  (/usr/bin/utox+0x45c79a)
    #1 0x45dc12 in create_tray_icon (/usr/bin/utox+0x45dc12)
    #2 0x4139d4 in main (/usr/bin/utox+0x4139d4)
    #3 0x7f7daf9c782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x4146f8 in _start (/usr/bin/utox+0x4146f8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
==11381==ABORTING

**Comment by redmanmale** [comment]
Possibly dup of #1064.
Try to use nigtly build from [here](https://build.tox.chat/view/uTox/job/uTox-nightly_build_linux_x86-64_debug/lastSuccessfulBuild/artifact/utox_linux_x86-64.tar.xz).

**Comment by pizdjuk** [comment]
crashes with segfault, dmesg output:

[20952.618837] utox[12722]: segfault at a23 ip 000000000044adc2 sp 00007ffe368277a0 error 4 in utox[400000+3cd000]

**Comment by pizdjuk** [comment]
Started with gdb:

Reading symbols from ./utox...done.
(gdb) run
Starting program: /home/dikiy/tmp/utox 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4fc1700 (LWP 12789)]
[New Thread 0x7ffff4ec0700 (LWP 12790)]
[Thread 0x7ffff4fc1700 (LWP 12789) exited]

Thread 1 "utox" received signal SIGSEGV, Segmentation fault.
0x000000000044adc2 in draw_tray_icon ()
    at /home/jenkins/workspace/uTox-nightly_build_linux_x86-64_debug/uTox/src/xlib/tray.c:95
95	/home/jenkins/workspace/uTox-nightly_build_linux_x86-64_debug/uTox/src/xlib/tray.c: no such file or directory

**Comment by GrayHatter** [comment]
@robinlinden is that build's libc static?

**Comment by pizdjuk** [comment]
linux-vdso.so.1 =>  (0x00007ffda7dae000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9f8880e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9f885f1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9f882e7000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f9f880df000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f9f87ec5000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f9f87b8a000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f9f87978000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f9f8776e000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f9f8752a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f9f87280000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f9f87065000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9f86e60000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9f86a96000)
	/lib64/ld-linux-x86-64.so.2 (0x000055fe29af5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f9f86891000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f9f8666e000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f9f86445000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9f8622b000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f9f86005000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9f85e01000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f9f85bfb000)

**Comment by GrayHatter** [comment]
@robinlinden 

tray.c:95 ->size_t   icon_size = &_binary_icons_utox_128x128_png_end - &_binary_icons_utox_128x128_png_start;

seems the tray image isn't being linked correctly

**Comment by im-grey** [comment]
This has been happening to me too. It started today with uTox running everything just fine *unless* I said the string "invite 5" to the Groupbot. Then it crashed with this:

```
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
Chatlog:      Log read:	Error reading record 1 of length 3 at offset 0: stopping.
Chatlog:      Log read:	Error reading record 1 of length 6 at offset 0: stopping.
AL lib: (WW) alcCloseDevice: Releasing context 0xb20133c0
uTox Audio:   Audio out device set to null.
get_group:     index: 0 is out of bounds.
Group callback: gid 0 pid 0 change 0
Group callback: gid 0 pid 0 change 2
Group callback: gid 0 pid 1 change 0
Group callback: gid 0 pid 1 change 2
Group callback: gid 0 pid 2 change 0
Group callback: gid 0 pid 2 change 2
Group callback: gid 0 pid 3 change 0
Group callback: gid 0 pid 3 change 2
Group callback: gid 0 pid 4 change 0
Group callback: gid 0 pid 4 change 2
Group callback: gid 0 pid 5 change 0
Group callback: gid 0 pid 5 change 2
Group callback: gid 0 pid 6 change 0
Group callback: gid 0 pid 6 change 2
Group callback: gid 0 pid 7 change 0
Group callback: gid 0 pid 7 change 2
Group callback: gid 0 pid 8 change 0
Group callback: gid 0 pid 8 change 2
get_group:     index: 1 is out of bounds.
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 0 receipt_number 2 

Group callback: gid 1 pid 0 change 0
Group callback: gid 1 pid 0 change 2
Group callback: gid 1 pid 1 change 0
Group callback: gid 1 pid 1 change 2
Group callback: gid 1 pid 2 change 0
Group callback: gid 1 pid 2 change 2
Group callback: gid 1 pid 3 change 0
Group callback: gid 1 pid 3 change 2
Group callback: gid 1 pid 4 change 0
Group callback: gid 1 pid 4 change 2
Group callback: gid 1 pid 5 change 0
Group callback: gid 1 pid 5 change 2
Group callback: gid 1 pid 6 change 0
Group callback: gid 1 pid 6 change 2
Group callback: gid 1 pid 7 change 0
Group callback: gid 1 pid 7 change 2
Group callback: gid 1 pid 8 change 0
Group callback: gid 1 pid 8 change 2
Group callback: gid 1 pid 9 change 0
Group callback: gid 1 pid 9 change 2
Group callback: gid 1 pid 10 change 0
Group callback: gid 1 pid 10 change 2
Group callback: gid 1 pid 11 change 0
Group callback: gid 1 pid 11 change 2
Group callback: gid 1 pid 12 change 0
Group callback: gid 1 pid 12 change 2
Group callback: gid 1 pid 13 change 0
Group callback: gid 1 pid 13 change 2
Group callback: gid 1 pid 14 change 0
Group callback: gid 1 pid 14 change 2
Group callback: gid 1 pid 15 change 0
Group callback: gid 1 pid 15 change 2
=================================================================
==16862==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xbf8a9cf0 at pc 0x080ed6c7 bp 0xbf8a9ae8 sp 0xbf8a9ad8
READ of size 1 at 0xbf8a9cf0 thread T0
    #0 0x80ed6c6 in utf8_len_read (/usr/bin/utox+0x80ed6c6)
    #1 0x80a198e in textwidth (/usr/bin/utox+0x80a198e)
    #2 0x80a4859  (/usr/bin/utox+0x80a4859)
    #3 0x80e4c7a  (/usr/bin/utox+0x80e4c7a)
    #4 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #5 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #6 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #7 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #8 0x80e50ae in panel_draw (/usr/bin/utox+0x80e50ae)
    #9 0x80588b4 in main (/usr/bin/utox+0x80588b4)
    #10 0xb77e7636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #11 0x8059a90  (/usr/bin/utox+0x8059a90)

Address 0xbf8a9cf0 is located in stack of thread T0 at offset 160 in frame
    #0 0x80a422f  (/usr/bin/utox+0x80a422f)

  This frame has 1 object(s):
    [32, 160) 'buf' <== Memory access at offset 160 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow ??:0 utf8_len_read
Shadow bytes around the buggy address:
  0x37f15340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37f15350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37f15360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x37f15370: f1 f1 04 f4 f4 f4 f3 f3 f3 f3 00 00 00 00 00 00
  0x37f15380: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00
=>0x37f15390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3
  0x37f153a0: f3 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x37f153b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37f153c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37f153d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37f153e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==16862==ABORTING
```

Then after that, it would crash just after start when I started to see my icon bubble turn green and all my online friends would change to green.

```
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
Chatlog:      Log read:	Error reading record 1 of length 3 at offset 0: stopping.
Chatlog:      Log read:	Error reading record 1 of length 6 at offset 0: stopping.
AL lib: (WW) alcCloseDevice: Releasing context 0xb21133c0
uTox Audio:   Audio out device set to null.
get_group:     index: 0 is out of bounds.
Group callback: gid 0 pid 0 change 0
Group callback: gid 0 pid 0 change 2
Group callback: gid 0 pid 1 change 0
Group callback: gid 0 pid 1 change 2
Group callback: gid 0 pid 2 change 0
Group callback: gid 0 pid 2 change 2
Group callback: gid 0 pid 3 change 0
Group callback: gid 0 pid 3 change 2
Group callback: gid 0 pid 4 change 0
Group callback: gid 0 pid 4 change 2
Group callback: gid 0 pid 5 change 0
Group callback: gid 0 pid 5 change 2
Group callback: gid 0 pid 6 change 0
Group callback: gid 0 pid 6 change 2
Group callback: gid 0 pid 7 change 0
Group callback: gid 0 pid 7 change 2
Group callback: gid 0 pid 8 change 0
Group callback: gid 0 pid 8 change 2
Group callback: gid 0 pid 9 change 0
Group callback: gid 0 pid 9 change 2
Group callback: gid 0 pid 10 change 0
Group callback: gid 0 pid 10 change 2
Group callback: gid 0 pid 11 change 0
Group callback: gid 0 pid 11 change 2
Group callback: gid 0 pid 12 change 0
Group callback: gid 0 pid 12 change 2
Group callback: gid 0 pid 13 change 0
Group callback: gid 0 pid 13 change 2
Group callback: gid 0 pid 14 change 0
Group callback: gid 0 pid 14 change 2
Group callback: gid 0 pid 15 change 0
Group callback: gid 0 pid 15 change 2
Group callback: gid 0 pid 16 change 0
Group callback: gid 0 pid 16 change 2
Group callback: gid 0 pid 17 change 0
Group callback: gid 0 pid 17 change 2
Group callback: gid 0 pid 18 change 0
=================================================================
==17704==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xbfd1dd80 at pc 0x080ed6c7 bp 0xbfd1db78 sp 0xbfd1db68
READ of size 1 at 0xbfd1dd80 thread T0
    #0 0x80ed6c6 in utf8_len_read (/usr/bin/utox+0x80ed6c6)
    #1 0x80a198e in textwidth (/usr/bin/utox+0x80a198e)
    #2 0x80a4859  (/usr/bin/utox+0x80a4859)
    #3 0x80e4c7a  (/usr/bin/utox+0x80e4c7a)
    #4 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #5 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #6 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #7 0x80e4d23  (/usr/bin/utox+0x80e4d23)
    #8 0x80e50ae in panel_draw (/usr/bin/utox+0x80e50ae)
    #9 0x80588b4 in main (/usr/bin/utox+0x80588b4)
    #10 0xb7879636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #11 0x8059a90  (/usr/bin/utox+0x8059a90)

Address 0xbfd1dd80 is located in stack of thread T0 at offset 160 in frame
    #0 0x80a422f  (/usr/bin/utox+0x80a422f)

  This frame has 1 object(s):
    [32, 160) 'buf' <== Memory access at offset 160 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow ??:0 utf8_len_read
Shadow bytes around the buggy address:
  0x37fa3b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3b80: f1 f1 f1 f1 04 f4 f4 f4 f3 f3 f3 f3 00 00 00 00
  0x37fa3b90: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x37fa3ba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x37fa3bb0:[f3]f3 f3 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x37fa3bc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3bd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3be0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3bf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x37fa3c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==17704==ABORTING
```

I'm running the latest uTox in the repo on the latest Xbuntu.

**Comment by redmanmale** [comment]
> utf8_len_read

It looks like a different problem entirely. I'll try to reproduce.
