### ISSUE TITLE
crashes with code c0000094 while trying to preview video using webcam VID_13D3&PID_5702

### ISSUE THREAD

**Issue by b-fett** [uTox/uTox#1176]
### Overview
Q|A
-- | --
uTox version| 0.16.1
OS |Windows 7 (6.1.7601)

### Issue
Webcam works fine with other soft.
For reference, similar problem there https://github.com/qTox/qTox/issues/4947

**Comment by jjgalvez** [comment]
Similar error on Linux
Ubuntu 16.04
uTox 0.16.1
Video preview cases causes it to crash
here is the terminal output:
jc@puker:~$ utox

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:3218:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:6378:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:6388:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:6438:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:6551:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(utox:12204): Gtk-WARNING **: Theme parsing error: gtk.css:6574:52: The :prelight pseudo-class is deprecated. Use :hover instead.
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
AL lib: (WW) alcCloseDevice: Releasing context 0x61200005f740
==12204==WARNING: AddressSanitizer failed to allocate 0xffffffff87d57e6c bytes
==12204==AddressSanitizer's allocator is terminating the process instead of returning 0
==12204==If you don't like this behavior set allocator_may_return_null=1
==12204==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator.cc:147 "((0)) != (0)" (0x0, 0x0)
    #0 0x7f9b8dc1d631  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa0631)
    #1 0x7f9b8dc225e3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa55e3)
    #2 0x7f9b8db9a425  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x1d425)
    #3 0x7f9b8dc20865  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa3865)
    #4 0x7f9b8db9fb4d  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x22b4d)
    #5 0x7f9b8dc155d2 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x985d2)
    #6 0x44dd26 in video_frame (/usr/bin/utox+0x44dd26)
    #7 0x4d9816 in utox_message_dispatch (/usr/bin/utox+0x4d9816)
    #8 0x45cb5b in doevent (/usr/bin/utox+0x45cb5b)
    #9 0x4139d1 in main (/usr/bin/utox+0x4139d1)
    #10 0x7f9b8d7d382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x414648 in _start (/usr/bin/utox+0x414648)

jc@puker:~$

**Comment by jjgalvez** [comment]
also tried the nightly build but that did not run so I went back to the stable build
