### ISSUE TITLE
Excutable fails to open after checkinstall

### ISSUE THREAD

**Issue by Ub3rZ4cH** [uTox/uTox#1256]
### Overview

1. uTox version: 0.17.0
2. Operating system: Xubuntu
3. Desktop Environment/Window Manager (Linux/BSD only): XFCE

### Issue

After building **git clone --recursive git://github.com/uTox/uTox.git**
I launch uTox from my menus and nothing happens, so I ran it through terminal and I get this thrown at me;

> Settings:     Unable to parse utox_save.ini.
=================================================================
==25179==ERROR: AddressSanitizer: global-buffer-overflow on address 0x556d581fe3c2 at pc 0x7f7e74ecef09 bp 0x7fff2cf9d050 sp 0x7fff2cf9c7e0
WRITE of size 3 at 0x556d581fe3c2 thread T0
    #0 0x7f7e74ecef08 in __interceptor_vsnprintf (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xa0f08)
    #1 0x7f7e74ecf286 in snprintf (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xa1286)
    #2 0x556d57da075b in config_load (/home/jake/uTox/build/utox+0x23a75b)
    #3 0x556d57de5889 in utox_init (/home/jake/uTox/build/utox+0x27f889)
    #4 0x556d57c09f27 in main (/home/jake/uTox/build/utox+0xa3f27)
    #5 0x7f7e74a5eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #6 0x556d57be02f9 in _start (/home/jake/uTox/build/utox+0x7a2f9)

0x556d581fe3c2 is located 62 bytes to the left of global variable 'edit_profile_password_data' defined in '/home/jake/uTox/src/layout/settings.c:1313:13' (0x556d581fe400) of size 65535
0x556d581fe3c2 is located 0 bytes to the right of global variable 'edit_video_fps_data' defined in '/home/jake/uTox/src/layout/settings.c:1312:13' (0x556d581fe3c0) of size 2
SUMMARY: AddressSanitizer: global-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xa0f08) in __interceptor_vsnprintf
Shadow bytes around the buggy address:
  0x0aae2b037c20: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037c30: 00 00 00 00 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aae2b037c40: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x0aae2b037c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037c60: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
=>0x0aae2b037c70: 00 f9 f9 f9 f9 f9 f9 f9[02]f9 f9 f9 f9 f9 f9 f9
  0x0aae2b037c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037c90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037ca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037cb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aae2b037cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25179==ABORTING

Coming from solving a few issues here - https://github.com/uTox/uTox/issues/1255
I removed everything and tried again and still got the same.

**Comment by Ub3rZ4cH** [comment]
**Solution:** - Compile from [https://github.com/uTox/uTox/releases/download/v0.17.0/uTox-0.17.0-full.tar.gz](url) VS git clone --recursive git://github.com/uTox/uTox.git as the guide in the https://github.com/uTox/uTox/blob/develop/docs/BUILD.md#ubuntu says. 

I thought I tried that and got the same results, but apparently not, because it worked this time round.

https://github.com/eclipseo said - 

> Don't clone the GIT repo, you need to use the archive "uTox-0.17.0-full.tar.gz" from https://github.com/uTox/uTox/releases to get the whole 3rd party.

But at the time I thought he was referencing the 3rd party errors I was getting. 

I can now launch and run uTox 0.17.0 just fine.
