### ISSUE TITLE
Segfault on audio test

### ISSUE THREAD

**Issue by v2e** [uTox/uTox#1283]
### Overview

1. uTox version: git cloned commit a86aa938f93e4691d74cd342f2d91e904d44ea17
2. Operating system: Gentoo GNU/Linux
3. Desktop Environment/Window Manager (Linux/BSD only): Xfce

### Issue

I have just cloned the current git repository (commit a86aa938f93e4691d74cd342f2d91e904d44ea17) and compiled it on my Gentoo system. Now if I try to run an audio test in uTox, it crashes immediately printing this in the console:

```
ASAN:DEADLYSIGNAL
=================================================================
==22972==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7f921568df00 bp 0x7f9206d08a70 sp 0x7f9206d08148 T4)
==22972==The signal is caused by a READ memory access.
==22972==Hint: address points to the zero page.
    #0 0x7f921568deff  (/usr/lib64/libtoxcore.so.2+0x35eff)
    #1 0x7f9215690542 in tox_conference_get_chatlist_size (/usr/lib64/libtoxcore.so.2+0x38542)
    #2 0x562d00e3fb96 in utox_audio_thread (/usr/bin/utox+0x144b96)
    #3 0x7f9214e0e8d9 in start_thread (/lib64/libpthread.so.0+0x78d9)
    #4 0x7f92159a85be in clone (/lib64/libc.so.6+0x1025be)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib64/libtoxcore.so.2+0x35eff) 
Thread T4 created by T2 here:
    #0 0x7f9215c9ed5e in pthread_create (/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libasan.so.4+0x37d5e)
    #1 0x562d00ddabf8 in thread (/usr/bin/utox+0xdfbf8)
    #2 0x562d00e41160 in utox_av_ctrl_thread (/usr/bin/utox+0x146160)
    #3 0x7f9214e0e8d9 in start_thread (/lib64/libpthread.so.0+0x78d9)

Thread T2 created by T0 here:
    #0 0x7f9215c9ed5e in pthread_create (/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libasan.so.4+0x37d5e)
    #1 0x562d00ddabf8 in thread (/usr/bin/utox+0xdfbf8)
    #2 0x562d00d71e86 in main (/usr/bin/utox+0x76e86)
    #3 0x7f92158c6f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

==22972==ABORTING
```
I also tried to run it from the GDB shell and do the backtrace. Here is the output:

```
Thread 5 "utox" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe7fe3700 (LWP 22767)]
0x00007ffff6840f00 in count_chatlist () from /usr/lib64/libtoxcore.so.2
(gdb) backtrace 
#0  0x00007ffff6840f00 in count_chatlist () from /usr/lib64/libtoxcore.so.2
#1  0x00007ffff6843543 in tox_conference_get_chatlist_size ()
   from /usr/lib64/libtoxcore.so.2
#2  0x0000555555698b97 in utox_audio_thread ()
#3  0x00007ffff5fc18da in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff6b5b5bf in clone () from /lib64/libc.so.6
```

**Comment by GrayHatter** [comment]
Can you describe what you mean by audio test?

**Comment by v2e** [comment]
I mean going to Settings --> Audio/Video --> and push the green telephone button to check if the sound is captured and played correctly.

**Comment by endoffile78** [comment]
Do you have the latest version of toxcore? There was a bug in toxcore at one point where it would return the wrong structure and it affected this part of our code.

**Comment by v2e** [comment]
@endoffile78 Yes, you were right. I downloaded the latest Toxcore git, compiled it, and the problem has gone. Now it works properly. Thank you!
