### ISSUE TITLE
uTox can crash on ft_update_resumable

### ISSUE THREAD

**Issue by qsniyg** [uTox/uTox#1331]
### Overview

1. uTox version: Latest git
2. Operating system: Linux
3. Desktop Environment/Window Manager (Linux/BSD only): i3

### Issue

uTox can crash in this way:

```
AddressSanitizer==31347==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f243c5d2b44 bp 0x7f2435d578e0 sp 0x7f2435d577c8 T3)
==31347==The signal is caused by a READ memory access.
==31347==Hint: address points to the zero page.
 #0 0x7f243c5d2b43 in __GI___fileno (/usr/lib/libc.so.6+0x78b43)
 #1 0x55b33ef5fd2c in ft_update_resumable (/usr/local/bin/utox+0x7fd2c)
 #2 0x55b33ef60f16 in break_file (/usr/local/bin/utox+0x80f16)
 #3 0x55b33ef62e69 in ft_friend_offline (/usr/local/bin/utox+0x82e69)
```

I'm not sure what exactly causes it.

**Comment by g4jc** [comment]
Just had a very similar crash with the same setup, not sure if the bug is identical, but it looks pretty close.
Mine occurred shortly after a friend went offline, which matches `ft_friend_offline` in the trace.

```
FileTransfer: Can't decon a FT that doesn't exist!
ASAN:DEADLYSIGNAL
=================================================================
ASAN:DEADLYSIGNAL
==16817==AddressSanitizer: while reporting a bug found another one. Ignoring.
==16817==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fb35a751554 bp 0x7fb3475efed0 sp 0x7fb3475efd90 T3)
==16817==The signal is caused by a READ memory access.
==16817==Hint: address points to the zero page.
    #0 0x7fb35a751553 in fileno (/lib64/libc.so.6+0x7e553)
    #1 0x55e36a367cee  (/usr/bin/utox+0x112cee)
    #2 0x55e36a37a0c7  (/usr/bin/utox+0x1250c7)
    #3 0x55e36a37a380 in ft_friend_offline (/usr/bin/utox+0x125380)
    #4 0x55e36a35efca  (/usr/bin/utox+0x109fca)
    #5 0x7fb35a6a49c4  (/usr/lib64/libtoxcore.so.2+0x319c4)
    #6 0x7fb35a6a4a95  (/usr/lib64/libtoxcore.so.2+0x31a95)
    #7 0x7fb35a6a5661  (/usr/lib64/libtoxcore.so.2+0x32661)
    #8 0x7fb35a6a0e2f  (/usr/lib64/libtoxcore.so.2+0x2de2f)
    #9 0x7fb35a698521  (/usr/lib64/libtoxcore.so.2+0x25521)
    #10 0x7fb35a69919e  (/usr/lib64/libtoxcore.so.2+0x2619e)
    #11 0x7fb35a6994e4  (/usr/lib64/libtoxcore.so.2+0x264e4)
    #12 0x7fb35a690db1  (/usr/lib64/libtoxcore.so.2+0x1ddb1)
    #13 0x7fb35a68f9c3  (/usr/lib64/libtoxcore.so.2+0x1c9c3)
    #14 0x7fb35a690744 in do_TCP_connection (/usr/lib64/libtoxcore.so.2+0x1d744)
    #15 0x7fb35a692b23 in do_tcp_connections (/usr/lib64/libtoxcore.so.2+0x1fb23)
    #16 0x7fb35a699a20 in do_net_crypto (/usr/lib64/libtoxcore.so.2+0x26a20)
    #17 0x7fb35a6a7cfc in do_messenger (/usr/lib64/libtoxcore.so.2+0x34cfc)
    #18 0x7fb35a6b1b88 in tox_iterate (/usr/lib64/libtoxcore.so.2+0x3eb88)
    #19 0x55e36a3617a1 in toxcore_thread (/usr/bin/utox+0x10c7a1)
    #20 0x7fb35a3cb2e6 in start_thread (/lib64/libpthread.so.0+0x82e6)
    #21 0x7fb35a7ce47e in clone (/lib64/libc.so.6+0xfb47e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libc.so.6+0x7e553) in fileno
Thread T3 created by T0 here:
    #0 0x7fb35a8a4c47 in __interceptor_pthread_create /var/tmp/portage/sys-devel/gcc-7.3.0-r6/work/gcc-7.3.0/libsanitizer/asan/asan_interceptors.cc:243
    #1 0x55e36a2fb4fd in thread (/usr/bin/utox+0xa64fd)
    #2 0x55e36a2d0a26 in main (/usr/bin/utox+0x7ba26)
    #3 0x7fb35a6f6c0d in __libc_start_main (/lib64/libc.so.6+0x23c0d)

==16817==ABORTING
```

Also a possible duplicate of #934?
