### ISSUE TITLE
Test failure on s390x: LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by eclipseo** [uTox/uTox#1541]
On Fedora Rawhide, with the latest release 0.18.1, the build started to fail on s390x architecture, with a message regarding a memory leak:

```
+ /usr/bin/ctest --output-on-failure --force-new-ctest-process -j3
Test project /builddir/build/BUILD/uTox-0.18.1/redhat-linux-build
    Start 1: test_chatlog
    Start 2: test_chrono
1/2 Test #1: test_chatlog .....................   Passed    0.01 sec
2/2 Test #2: test_chrono ......................***Failed    0.15 sec
Running suite(s): Chrono
=================================================================
==2406587==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x3ff9e73034d in __interceptor_malloc (/lib64/libasan.so.6+0xb034d)
    #1 0x3ff9e584945 in emalloc (/lib64/libcheck.so.0+0x4945)
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x3ff9e73034d in __interceptor_malloc (/lib64/libasan.so.6+0xb034d)
    #1 0x3ff9e584945 in emalloc (/lib64/libcheck.so.0+0x4945)
SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).
=================================================================
==2406590==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x3ff9e73034d in __interceptor_malloc (/lib64/libasan.so.6+0xb034d)
    #1 0x3ff9e584945 in emalloc (/lib64/libcheck.so.0+0x4945)
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x3ff9e73034d in __interceptor_malloc (/lib64/libasan.so.6+0xb034d)
    #1 0x3ff9e584945 in emalloc (/lib64/libcheck.so.0+0x4945)
SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).
0%: Checks: 2, Failures: 0, Errors: 2
```

**Comment by GrayHatter** [comment]
IIRC the chrono module should be disable by default, I don't think any part of uTox is currently using it. If it's not disabled in the build reopen this one, or a new issue and I'll fix it?
