### ISSUE TITLE
uTox segfaults if the "end" key is pressed when the message input box is empty

### ISSUE THREAD

**Issue by Encrypt** [uTox/uTox#417]
This bug -- found by chance -- is reproducible on probably all versions of uTox.

To reproduce, simply press the "end" key in the message input box, when it is empty.
This will immediately make uTox segfault.

**Comment by cebe** [comment]
gdb backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004babb0 in utf8_len (data=0x1009d233f <error: Cannot access memory at address 0x1009d233f>)
    at src/util.c:224
224	    if(!(*data & 0x80)) {
(gdb) bt
#0  0x00000000004babb0 in utf8_len (
    data=0x1009d233f <error: Cannot access memory at address 0x1009d233f>) at src/util.c:224
#1  0x00000000004d9daa in edit_char (ch=65367, control=true, flags=16 '\020') at src/ui/edit.c:614
#2  0x00000000004e4829 in doevent (event=...) at src/xlib/event.c:414
#3  0x00000000004e8a9b in main (argc=2, argv=0x7fffffffe2b8) at src/xlib/main.c:1274
```

**Comment by redmanmale** [comment]
Confirmed on Windows 7 and 8.1

**Comment by GrayHatter** [comment]
it's a simple fix, just ignore end key when length is empty
