### ISSUE TITLE
Crash on button click

### ISSUE THREAD

**Issue by MageSlayer** [uTox/uTox#730]
Debug build shows following.
Tested under Linux x64 3b7ddb5e365f6be4cfd5ee897e76bc13b8a172ef

```
F-List:       Trying to switch to an item that we shouldn't be selecting
F-List:       Trying to switch to an item that we shouldn't be selecting
uToxAV:       Change state with an error, this should never happen. Please send bug report!
uToxAV:       Change state with an error, this should never happen. Please send bug report!
=================================================================
==32429==ERROR: AddressSanitizer: attempting double-free on 0x60c000007480 in thread T0:
    #0 0x7ffff6f59b42 in __interceptor_realloc (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libasan.so.1+0x57b42)
    #1 0x61b791 in edit_do /home/denis/temp/utox/uTox/src/ui/edit.c:363
    #2 0x61df0c in edit_char /home/denis/temp/utox/uTox/src/ui/edit.c:734
    #3 0x5ffa8a in doevent /home/denis/temp/utox/uTox/src/xlib/event.c:422
    #4 0x5f9c64 in main /home/denis/temp/utox/uTox/src/xlib/main.c:950
    #5 0x7ffff3cd76cf in __libc_start_main (/lib64/libc.so.6+0x206cf)
    #6 0x412298 in _start (/home/denis/temp/utox/uTox/utox+0x412298)

0x60c000007480 is located 0 bytes inside of 128-byte region [0x60c000007480,0x60c000007500)
freed by thread T0 here:
    #0 0x7ffff6f595b1 in __interceptor_free (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libasan.so.1+0x575b1)
    #1 0x42b18a in friend_free /home/denis/temp/utox/uTox/src/friend.c:338
    #2 0x5e4b71 in utox_message_dispatch /home/denis/temp/utox/uTox/src/utox.c:418
    #3 0x600b3e in doevent /home/denis/temp/utox/uTox/src/xlib/event.c:571
    #4 0x5f9c64 in main /home/denis/temp/utox/uTox/src/xlib/main.c:950
    #5 0x7ffff3cd76cf in __libc_start_main (/lib64/libc.so.6+0x206cf)

previously allocated by thread T0 here:
    #0 0x7ffff6f59b42 in __interceptor_realloc (/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libasan.so.1+0x57b42)
    #1 0x61b791 in edit_do /home/denis/temp/utox/uTox/src/ui/edit.c:363
    #2 0x61bef9 in edit_char /home/denis/temp/utox/uTox/src/ui/edit.c:443
    #3 0x5ffaf1 in doevent /home/denis/temp/utox/uTox/src/xlib/event.c:424
    #4 0x5f9cb8 in main /home/denis/temp/utox/uTox/src/xlib/main.c:956
    #5 0x7ffff3cd76cf in __libc_start_main (/lib64/libc.so.6+0x206cf)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_realloc
==32429==ABORTING

```

**Comment by GrayHatter** [comment]
Looks like the realloc call. This is a false positive we should fix

**Comment by GrayHatter** [comment]
@robinlinden did you touch this in your last cleanup pull?

**Comment by robinlinden** [comment]
No. Most of that code is at least 6 months old. Someone still has to take a look at this.

**Comment by GrayHatter** [comment]
@MageSlayer what button did you click?

**Comment by MageSlayer** [comment]
That was quite long ago, so I don't remember for sure.
It seems it was related to "Settings"-"Advanced". 
"SOCKS 5" input I guess.

**Comment by redmanmale** [comment]
Reproduce on v.0.16.1 on Ubuntu 16.04 and Windows 7 x64.
Just quickly toggle several times any one of switches: IPv6, UDP, Proxy, Force proxy.
[Log](https://gist.github.com/redmanmale/e48ff8aac82518eea1ae859236e0b395).

**Comment by redmanmale** [comment]
There's too much open issues about the same bug.
