### ISSUE TITLE
Ubuntu 17.10 support

### ISSUE THREAD

**Issue by nazar-pc** [uTox/uTox#897]
I completely understand that 17.10 will be released in several months, but I'm trying to run 17.04 amd64 build already and hitting following issue:
```
=================================================================
==12194==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x608000005176 at pc 0x7f12f0b71033 bp 0x7fffbb6e4ad0 sp 0x7fffbb6e4278
READ of size 1 at 0x608000005176 thread T0
    #0 0x7f12f0b71032  (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x3d032)
    #1 0x55f642f42dcd in config_load (/usr/bin/utox+0xefdcd)
    #2 0x55f642f50773 in utox_init (/usr/bin/utox+0xfd773)
    #3 0x55f642ebb1d3 in main (/usr/bin/utox+0x681d3)
    #4 0x7f12f078d3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #5 0x55f642ebd1f9 in _start (/usr/bin/utox+0x6a1f9)

0x608000005176 is located 1 bytes to the right of 85-byte region [0x608000005120,0x608000005175)
allocated by thread T0 here:
    #0 0x7f12f0bfb080 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7080)
    #1 0x55f642f418ac in utox_data_load_utox (/usr/bin/utox+0xee8ac)
    #2 0x55f642f42615 in config_load (/usr/bin/utox+0xef615)
    #3 0x55f642f50773 in utox_init (/usr/bin/utox+0xfd773)
    #4 0x55f642ebb1d3 in main (/usr/bin/utox+0x681d3)
    #5 0x7f12f078d3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x3d032) 
Shadow bytes around the buggy address:
  0x0c107fff89d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff89e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff89f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8a10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c107fff8a20: fa fa fa fa 00 00 00 00 00 00 00 00 00 00[05]fa
  0x0c107fff8a30: fa fa fa fa 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c107fff8a40: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff8a50: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c107fff8a60: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c107fff8a70: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12194==ABORTING
```

Could anyone take a look at this to make it run on 17.10?

**Comment by GrayHatter** [comment]
@robinlinden

**Comment by nazar-pc** [comment]
Tried static build, works fine. I'm wondering why not always distributing static builds, since 2MiB vs 6.7MiB doesn't seem to be a critical difference on modern machines.

**Comment by redmanmale** [comment]
Let's say there's Ubuntu 18.04 LTS and uTox works just fine on it.
