### ISSUE TITLE
Unable to open utox

### ISSUE THREAD

**Issue by Opfour** [uTox/uTox#940]
new install on ubu 17.04:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
tried installing using the instructions at https://tox.chat/download.html#gnulinux
no errors on install. getting the following response when trying to start from command line/terminal. no response when trying to start utox from apps menu.

```
~$ utox
Settings:     Unable to open utox_save.
Settings:     unable to load utox_save data
Gtk-Message: Failed to load module "topmenu-gtk-module"
==2317==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/asan/asan_interceptors.cc:364 "((__interception::real___cxa_throw)) != (0)" (0x0, 0x0)
    #0 0x7f1c3e00f80a  (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xd080a)
    #1 0x7f1c3e0161d3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xd71d3)
    #2 0x7f1c3df7093c in __interceptor___cxa_throw (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x3193c)
    #3 0x7f1c313487a5  (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x757a5)
    #4 0x7f1c3134b8fe  (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x788fe)
    #5 0x7f1c31309a6f  (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x36a6f)
    #6 0x7f1c31313b08 in mir::client::DefaultConnectionConfiguration::the_rpc_channel() (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x40b08)
    #7 0x7f1c313041a8 in mir_connect (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x311a8)
    #8 0x7f1c313054da in mir_connect_sync (/usr/lib/x86_64-linux-gnu/libmirclient.so.9+0x324da)
    #9 0x7f1c34ca4ff6  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0xa4ff6)
    #10 0x7f1c34c3a234 in gdk_display_manager_open_display (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x3a234)
    #11 0x7f1c35139e19 in gtk_init_check (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0+0x22de19)
    #12 0x7f1c35139e48 in gtk_init (/usr/lib/x86_64-linux-gnu/libgtk-3.so.0+0x22de48)
    #13 0x55f47c797f48 in ugtk_load (/usr/bin/utox+0xcef48)
    #14 0x55f47c73194e in main (/usr/bin/utox+0x6894e)
    #15 0x7f1c3db983f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #16 0x55f47c7331f9 in _start (/usr/bin/utox+0x6a1f9)
```
lil halp?

**Comment by redmanmale** [comment]
Ubuntu 17.04 lacks uTox support yet (#897).
Try static build.

**Comment by redmanmale** [comment]
Could not reproduce with 0.16.1.

**Comment by redmanmale** [comment]
Let's say there's Ubuntu 18.04 LTS and uTox 0.17.0
They are working together just fine.
